"""AUTO-GENERATED by tools/gen_test_all.py — do not edit by hand.

Flat view of the whole Canonizer UI suite: one physical ``def test_*`` per
case so VS Code shows a Run/Debug gutter icon on every test. Each method just
calls the real implementation in ``test_suites/*_tests.py`` — no logic lives
here. Regenerate after changing the suites:

    .venv/bin/python tools/gen_test_all.py
"""
import pytest

from test_suites import (
    BaseFlow,
    AuthRegistrationTests,
    TopicTests,
    CampTests,
    StatementTests,
    ForumNewsTests,
    BrowseSearchTests,
    ProfileUploadAccessTests,
    BacklogTests,
    MiscTests,
)


class TestPages(
    BaseFlow,
    AuthRegistrationTests,
    TopicTests,
    CampTests,
    StatementTests,
    ForumNewsTests,
    BrowseSearchTests,
    ProfileUploadAccessTests,
    BacklogTests,
    MiscTests,
):
    """Every test as a one-line delegating wrapper (see module docstring)."""


    # ---- AuthRegistrationTests ---------------------------------------
    def test_login_to_canonizer(self):
        """Test case: Login to canonizer."""
        return AuthRegistrationTests.test_login_to_canonizer(self)

    def test_register_page_mandatory_fields_are_marked_with_asterisk(self):
        """Test case: Register page mandatory fields are marked with asterisk."""
        return AuthRegistrationTests.test_register_page_mandatory_fields_are_marked_with_asterisk(self)

    def test_check_login_page_open_click_login_here_link(self):
        """Test case: Check login page open click login here link."""
        return AuthRegistrationTests.test_check_login_page_open_click_login_here_link(self)

    def test_click_on_login_button(self):
        """Test case: Click on login button."""
        return AuthRegistrationTests.test_click_on_login_button(self)

    def test_login_with_registered_credentials(self):
        """Test case: Login with registered credentials."""
        return AuthRegistrationTests.test_login_with_registered_credentials(self)

    def test_verify_the_login_with_blank_email(self):
        """Test case: Verify the login with blank email."""
        return AuthRegistrationTests.test_verify_the_login_with_blank_email(self)

    def test_verify_the_login_with_blank_password(self):
        """Test case: Verify the login with blank password."""
        return AuthRegistrationTests.test_verify_the_login_with_blank_password(self)

    def test_login_with_invalid_email(self):
        """Test case: Login with invalid email."""
        return AuthRegistrationTests.test_login_with_invalid_email(self)

    def test_login_page_mandatory_fields_are_marked_with_asterisk(self):
        """Test case: Login page mandatory fields are marked with asterisk."""
        return AuthRegistrationTests.test_login_page_mandatory_fields_are_marked_with_asterisk(self)

    def test_login_remember_me_is_selected_by_default(self):
        """Test case: Login remember me is selected by default."""
        return AuthRegistrationTests.test_login_remember_me_is_selected_by_default(self)

    def test_login_register_now_link(self):
        """Test case: Login register now link."""
        return AuthRegistrationTests.test_login_register_now_link(self)

    def test_forgot_password_link(self):
        """Test case: Forgot password link."""
        return AuthRegistrationTests.test_forgot_password_link(self)

    @pytest.mark.parametrize('provider', ['facebook', 'google', 'linkedin', 'github'])
    def test_login_social_provider_is_available(self, provider):
        """Test case: Login social provider is available."""
        return AuthRegistrationTests.test_login_social_provider_is_available(self, provider)

    def test_logout(self):
        """Test case: Logout."""
        return AuthRegistrationTests.test_logout(self)

    def test_forgot_password_with_blank_email(self):
        """Test case: Forgot password with blank email."""
        return AuthRegistrationTests.test_forgot_password_with_blank_email(self)

    def test_forgot_password_with_invalid_email(self):
        """Test case: Forgot password with invalid email."""
        return AuthRegistrationTests.test_forgot_password_with_invalid_email(self)

    def test_forgot_password_with_unregistered_email(self):
        """Test case: Forgot password with unregistered email."""
        return AuthRegistrationTests.test_forgot_password_with_unregistered_email(self)

    def test_close_login_modal(self):
        """Test case: Close login modal."""
        return AuthRegistrationTests.test_close_login_modal(self)

    def test_forgot_password_otp_with_invalid_code(self):
        """Test case: Forgot password otp with invalid code."""
        return AuthRegistrationTests.test_forgot_password_otp_with_invalid_code(self)

    def test_forgot_password_otp_with_blank_code(self):
        """Test case: Forgot password otp with blank code."""
        return AuthRegistrationTests.test_forgot_password_otp_with_blank_code(self)

    def test_resend_forgot_password_otp(self):
        """Test case: Resend forgot password otp."""
        return AuthRegistrationTests.test_resend_forgot_password_otp(self)

    def test_reset_password_with_mismatched_passwords(self):
        """Test case: Reset password with mismatched passwords."""
        return AuthRegistrationTests.test_reset_password_with_mismatched_passwords(self)

    def test_click_create_topic_without_user_login(self):
        """Test case: Click create topic without user login."""
        return AuthRegistrationTests.test_click_create_topic_without_user_login(self)

    def test_upload_file_without_userlogin(self):
        """Test case: Upload file without userlogin."""
        return AuthRegistrationTests.test_upload_file_without_userlogin(self)


    # ---- TopicTests --------------------------------------------------
    def test_click_create_new_topic_page_button(self):
        """Test case: Click create new topic page button."""
        return TopicTests.test_click_create_new_topic_page_button(self)

    def test_create_topic_with_blank_topic_name(self):
        """Test case: Create topic with blank topic name."""
        return TopicTests.test_create_topic_with_blank_topic_name(self)

    def test_create_topic_name_with_valid_data(self):
        """Test case: Create topic name with valid data."""
        return TopicTests.test_create_topic_name_with_valid_data(self)

    def test_create_same_topic_name_with_valid_data(self):
        """Test case: Create same topic name with valid data."""
        return TopicTests.test_create_same_topic_name_with_valid_data(self)

    def test_create_same_topic_name_error_link(self):
        """Test case: Create same topic name error link."""
        return TopicTests.test_create_same_topic_name_error_link(self)

    def test_create_topic_with_special_chars(self):
        """Test case: Create topic with special chars."""
        return TopicTests.test_create_topic_with_special_chars(self)

    def test_create_topic_without_entering_mandatory_fields(self):
        """Test case: Create topic without entering mandatory fields."""
        return TopicTests.test_create_topic_without_entering_mandatory_fields(self)

    def test_create_topic_mandatory_fields_are_marked_with_asterisk(self):
        """Test case: Create topic mandatory fields are marked with asterisk."""
        return TopicTests.test_create_topic_mandatory_fields_are_marked_with_asterisk(self)

    def test_create_topic_with_trailing_spaces(self):
        """Test case: Create topic with trailing spaces."""
        return TopicTests.test_create_topic_with_trailing_spaces(self)

    def test_create_topic_using_enter_key(self):
        """Test case: Create topic using enter key."""
        return TopicTests.test_create_topic_using_enter_key(self)

    def test_create_topic_with_only_mandatory_fields(self):
        """Test case: Create topic with only mandatory fields."""
        return TopicTests.test_create_topic_with_only_mandatory_fields(self)

    def test_cancel_create_topic(self):
        """Test case: Cancel create topic."""
        return TopicTests.test_cancel_create_topic(self)

    def test_load_topic_history_page(self):
        """Test case: Load topic history page."""
        return TopicTests.test_load_topic_history_page(self)

    def test_verify_topic_name_on_topic_history_page(self):
        """Test case: Verify topic name on topic history page."""
        return TopicTests.test_verify_topic_name_on_topic_history_page(self)

    def test_verify_submit_topic_update_button(self):
        """Test case: Verify submit topic update button."""
        return TopicTests.test_verify_submit_topic_update_button(self)

    def test_verify_cancel_button_functionality_on_topic_update_page(self):
        """Test case: Verify cancel button functionality on topic update page."""
        return TopicTests.test_verify_cancel_button_functionality_on_topic_update_page(self)

    def test_update_topic_name(self):
        """Test case: Update topic name."""
        return TopicTests.test_update_topic_name(self)

    def test_topic_update_preview(self):
        """Test case: Topic update preview."""
        return TopicTests.test_topic_update_preview(self)

    def test_topic_preview_cancel(self):
        """Test case: Topic preview cancel."""
        return TopicTests.test_topic_preview_cancel(self)

    def test_topic_preview_submitter_nickname(self):
        """Test case: Topic preview submitter nickname."""
        return TopicTests.test_topic_preview_submitter_nickname(self)

    def test_compare_topic_versions(self):
        """Test case: Compare topic versions."""
        return TopicTests.test_compare_topic_versions(self)

    def test_topic_comparison_agreement_link(self):
        """Test case: Topic comparison agreement link."""
        return TopicTests.test_topic_comparison_agreement_link(self)

    def test_topic_comparison_create_topic_button(self):
        """Test case: Topic comparison create topic button."""
        return TopicTests.test_topic_comparison_create_topic_button(self)

    def test_topic_comparison_back_button(self):
        """Test case: Topic comparison back button."""
        return TopicTests.test_topic_comparison_back_button(self)

    def test_topic_history_view_this_version(self):
        """Test case: Topic history view this version."""
        return TopicTests.test_topic_history_view_this_version(self)

    def test_browse_start_topic(self):
        """Test case: Browse start topic."""
        return TopicTests.test_browse_start_topic(self)

    def test_browse_only_my_topics(self):
        """Test case: Browse only my topics."""
        return TopicTests.test_browse_only_my_topics(self)

    def test_browse_search_by_topic_tag(self):
        """Test case: Browse search by topic tag."""
        return TopicTests.test_browse_search_by_topic_tag(self)

    def test_advanced_search_topic_tab_navigation(self):
        """Test case: Advanced search topic tab navigation."""
        return TopicTests.test_advanced_search_topic_tab_navigation(self)

    def test_advanced_search_topic_review_filter_route(self):
        """Test case: Advanced search topic review filter route."""
        return TopicTests.test_advanced_search_topic_review_filter_route(self)

    def test_advanced_search_topic_pagination_visibility(self):
        """Test case: Advanced search topic pagination visibility."""
        return TopicTests.test_advanced_search_topic_pagination_visibility(self)

    def test_footer_create_topic_button(self):
        """Test case: Footer create topic button."""
        return TopicTests.test_footer_create_topic_button(self)

    def test_authentication_expiry_for_create_topic(self):
        """Test case: Authentication expiry for create topic."""
        return TopicTests.test_authentication_expiry_for_create_topic(self)

    def test_authentication_footer_create_topic(self):
        """Test case: Authentication footer create topic."""
        return TopicTests.test_authentication_footer_create_topic(self)

    def test_authentication_topic_history(self):
        """Test case: Authentication topic history."""
        return TopicTests.test_authentication_topic_history(self)

    def test_topic_name_in_recent_activities(self):
        """Test case: Topic name in recent activities."""
        return TopicTests.test_topic_name_in_recent_activities(self)

    def test_preferences_topic_tag_search(self):
        """Test case: Preferences topic tag search."""
        return TopicTests.test_preferences_topic_tag_search(self)

    def test_create_topic_edit_draft_crash(self):
        """Test case: Create topic edit draft crash."""
        return TopicTests.test_create_topic_edit_draft_crash(self)

    def test_asp_old_urls_for_topics(self):
        """Test case: Asp old urls for topics."""
        return TopicTests.test_asp_old_urls_for_topics(self)


    # ---- CampTests ---------------------------------------------------
    def test_topic_comparison_create_camp_button(self):
        """Test case: Topic comparison create camp button."""
        return CampTests.test_topic_comparison_create_camp_button(self)

    def test_load_create_camp_page(self):
        """Test case: Load create camp page."""
        return CampTests.test_load_create_camp_page(self)

    def test_create_camp_with_valid_data(self):
        """Test case: Create camp with valid data."""
        return CampTests.test_create_camp_with_valid_data(self)

    def test_create_camp_with_blank_camp_name(self):
        """Test case: Create camp with blank camp name."""
        return CampTests.test_create_camp_with_blank_camp_name(self)

    def test_create_camp_with_duplicate_camp_name(self):
        """Test case: Create camp with duplicate camp name."""
        return CampTests.test_create_camp_with_duplicate_camp_name(self)

    def test_create_camp_with_invalid_camp_about_url(self):
        """Test case: Create camp with invalid camp about url."""
        return CampTests.test_create_camp_with_invalid_camp_about_url(self)

    def test_create_camp_without_entering_data_in_mandatory_fields(self):
        """Test case: Create camp without entering data in mandatory fields."""
        return CampTests.test_create_camp_without_entering_data_in_mandatory_fields(self)

    def test_create_camp_mandatory_fields_are_marked_with_asterisk(self):
        """Test case: Create camp mandatory fields are marked with asterisk."""
        return CampTests.test_create_camp_mandatory_fields_are_marked_with_asterisk(self)

    def test_cancel_create_camp(self):
        """Test case: Cancel create camp."""
        return CampTests.test_cancel_create_camp(self)

    def test_create_camp_with_only_mandatory_fields(self):
        """Test case: Create camp with only mandatory fields."""
        return CampTests.test_create_camp_with_only_mandatory_fields(self)

    def test_update_camp_with_valid_data(self):
        """Test case: Update camp with valid data."""
        return CampTests.test_update_camp_with_valid_data(self)

    def test_verify_submit_camp_update_button(self):
        """Test case: Verify submit camp update button."""
        return CampTests.test_verify_submit_camp_update_button(self)

    def test_camp_preview_fields(self):
        """Test case: Camp preview fields."""
        return CampTests.test_camp_preview_fields(self)

    def test_camp_preview_cancel(self):
        """Test case: Camp preview cancel."""
        return CampTests.test_camp_preview_cancel(self)

    def test_camp_preview_submitter_nickname(self):
        """Test case: Camp preview submitter nickname."""
        return CampTests.test_camp_preview_submitter_nickname(self)

    def test_compare_camp_versions(self):
        """Test case: Compare camp versions."""
        return CampTests.test_compare_camp_versions(self)

    def test_camp_comparison_displays_both_versions(self):
        """Test case: Camp comparison displays both versions."""
        return CampTests.test_camp_comparison_displays_both_versions(self)

    def test_load_camp_manage_edit_page(self):
        """Test case: Load camp manage edit page."""
        return CampTests.test_load_camp_manage_edit_page(self)

    def test_submit_camp_update_with_invalid_url(self):
        """Test case: Submit camp update with invalid url."""
        return CampTests.test_submit_camp_update_with_invalid_url(self)

    def test_update_camp_with_duplicate_camp_name(self):
        """Test case: Update camp with duplicate camp name."""
        return CampTests.test_update_camp_with_duplicate_camp_name(self)

    def test_verify_cancel_button_functionality_on_camp_update_page(self):
        """Test case: Verify cancel button functionality on camp update page."""
        return CampTests.test_verify_cancel_button_functionality_on_camp_update_page(self)

    def test_verify_preview_button_functionality_on_camp_update_page(self):
        """Test case: Verify preview button functionality on camp update page."""
        return CampTests.test_verify_preview_button_functionality_on_camp_update_page(self)

    def test_create_news_available_for_child_camps(self):
        """Test case: Create news available for child camps."""
        return CampTests.test_create_news_available_for_child_camps(self)

    def test_advanced_search_camp_tab_navigation(self):
        """Test case: Advanced search camp tab navigation."""
        return CampTests.test_advanced_search_camp_tab_navigation(self)

    def test_advanced_search_camp_bydate_filter_route(self):
        """Test case: Advanced search camp bydate filter route."""
        return CampTests.test_advanced_search_camp_bydate_filter_route(self)

    def test_browse_profile_setting_supported_camps(self):
        """Test case: Browse profile setting supported camps."""
        return CampTests.test_browse_profile_setting_supported_camps(self)

    def test_authentication_expiry_for_create_camp(self):
        """Test case: Authentication expiry for create camp."""
        return CampTests.test_authentication_expiry_for_create_camp(self)

    def test_authentication_expiry_for_supported_camp(self):
        """Test case: Authentication expiry for supported camp."""
        return CampTests.test_authentication_expiry_for_supported_camp(self)

    def test_authentication_expiry_for_direct_supported_camp(self):
        """Test case: Authentication expiry for direct supported camp."""
        return CampTests.test_authentication_expiry_for_direct_supported_camp(self)

    def test_authentication_expiry_for_delegate_supported_camp(self):
        """Test case: Authentication expiry for delegate supported camp."""
        return CampTests.test_authentication_expiry_for_delegate_supported_camp(self)

    def test_support_camp_error_first_time(self):
        """Test case: Support camp error first time."""
        return CampTests.test_support_camp_error_first_time(self)

    def test_profile_page_direct_supported_camp_tab(self):
        """Test case: Profile page direct supported camp tab."""
        return CampTests.test_profile_page_direct_supported_camp_tab(self)

    def test_profile_page_delegate_supported_camp_tab(self):
        """Test case: Profile page delegate supported camp tab."""
        return CampTests.test_profile_page_delegate_supported_camp_tab(self)

    def test_asp_old_urls_for_camps(self):
        """Test case: Asp old urls for camps."""
        return CampTests.test_asp_old_urls_for_camps(self)


    # ---- StatementTests ----------------------------------------------
    def test_add_statement_for_archived_camp(self):
        """Test case: Add statement for archived camp."""
        return StatementTests.test_add_statement_for_archived_camp(self)

    def test_camp_statement_button(self):
        """Test case: Camp statement button."""
        return StatementTests.test_camp_statement_button(self)

    def test_load_camp_statement_page(self):
        """Test case: Load camp statement page."""
        return StatementTests.test_load_camp_statement_page(self)

    def test_add_camp_statement_with_valid_data(self):
        """Test case: Add camp statement with valid data."""
        return StatementTests.test_add_camp_statement_with_valid_data(self)

    def test_add_camp_statement_page_with_asterisk(self):
        """Test case: Add camp statement page with asterisk."""
        return StatementTests.test_add_camp_statement_page_with_asterisk(self)

    def test_add_camp_statement_without_mandatory_field(self):
        """Test case: Add camp statement without mandatory field."""
        return StatementTests.test_add_camp_statement_without_mandatory_field(self)

    def test_add_camp_statement_with_trailing_spaces(self):
        """Test case: Add camp statement with trailing spaces."""
        return StatementTests.test_add_camp_statement_with_trailing_spaces(self)

    def test_add_camp_statement_with_blank_data(self):
        """Test case: Add camp statement with blank data."""
        return StatementTests.test_add_camp_statement_with_blank_data(self)

    def test_cancel_create_camp_statement(self):
        """Test case: Cancel create camp statement."""
        return StatementTests.test_cancel_create_camp_statement(self)

    def test_preview_camp_statement(self):
        """Test case: Preview camp statement."""
        return StatementTests.test_preview_camp_statement(self)

    def test_camp_statement_template(self):
        """Test case: Camp statement template."""
        return StatementTests.test_camp_statement_template(self)

    def test_load_edit_camp_statement(self):
        """Test case: Load edit camp statement."""
        return StatementTests.test_load_edit_camp_statement(self)

    def test_edit_camp_statement(self):
        """Test case: Edit camp statement."""
        return StatementTests.test_edit_camp_statement(self)

    def test_update_camp_statement_with_mandatory_field(self):
        """Test case: Update camp statement with mandatory field."""
        return StatementTests.test_update_camp_statement_with_mandatory_field(self)

    def test_edit_camp_statement_with_trailing_spaces(self):
        """Test case: Edit camp statement with trailing spaces."""
        return StatementTests.test_edit_camp_statement_with_trailing_spaces(self)

    def test_edit_camp_statement_with_blank_data(self):
        """Test case: Edit camp statement with blank data."""
        return StatementTests.test_edit_camp_statement_with_blank_data(self)

    def test_compare_camp_statement(self):
        """Test case: Compare camp statement."""
        return StatementTests.test_compare_camp_statement(self)

    def test_advanced_search_camp_statement_tab_navigation(self):
        """Test case: Advanced search camp statement tab navigation."""
        return StatementTests.test_advanced_search_camp_statement_tab_navigation(self)

    def test_authentication_expiry_for_create_statement(self):
        """Test case: Authentication expiry for create statement."""
        return StatementTests.test_authentication_expiry_for_create_statement(self)

    def test_statement_image_more_than_5mb(self):
        """Test case: Statement image more than 5mb."""
        return StatementTests.test_statement_image_more_than_5mb(self)

    def test_statement_image_more_than_5mb_note(self):
        """Test case: Statement image more than 5mb note."""
        return StatementTests.test_statement_image_more_than_5mb_note(self)


    # ---- ForumNewsTests ----------------------------------------------
    def test_click_create_thread_button(self):
        """Test case: Click create thread button."""
        return ForumNewsTests.test_click_create_thread_button(self)

    def test_create_thread_with_valid_data(self):
        """Test case: Create thread with valid data."""
        return ForumNewsTests.test_create_thread_with_valid_data(self)

    def test_create_thread_with_blank_title(self):
        """Test case: Create thread with blank title."""
        return ForumNewsTests.test_create_thread_with_blank_title(self)

    def test_create_thread_with_special_chars(self):
        """Test case: Create thread with special chars."""
        return ForumNewsTests.test_create_thread_with_special_chars(self)

    def test_create_thread_with_blank_mandatory_fields(self):
        """Test case: Create thread with blank mandatory fields."""
        return ForumNewsTests.test_create_thread_with_blank_mandatory_fields(self)

    def test_create_thread_with_duplicate_title(self):
        """Test case: Create thread with duplicate title."""
        return ForumNewsTests.test_create_thread_with_duplicate_title(self)

    def test_create_thread_with_valid_data_with_enter_key(self):
        """Test case: Create thread with valid data with enter key."""
        return ForumNewsTests.test_create_thread_with_valid_data_with_enter_key(self)

    def test_create_thread_with_trailing_spaces(self):
        """Test case: Create thread with trailing spaces."""
        return ForumNewsTests.test_create_thread_with_trailing_spaces(self)

    def test_load_edit_thread_page(self):
        """Test case: Load edit thread page."""
        return ForumNewsTests.test_load_edit_thread_page(self)

    def test_edit_thread(self):
        """Test case: Edit thread."""
        return ForumNewsTests.test_edit_thread(self)

    def test_create_post(self):
        """Test case: Create post."""
        return ForumNewsTests.test_create_post(self)

    def test_edit_post(self):
        """Test case: Edit post."""
        return ForumNewsTests.test_edit_post(self)

    def test_delete_post(self):
        """Test case: Delete post."""
        return ForumNewsTests.test_delete_post(self)

    def test_load_my_threads_page(self):
        """Test case: Load my threads page."""
        return ForumNewsTests.test_load_my_threads_page(self)

    def test_load_top_10_threads_page(self):
        """Test case: Load top 10 threads page."""
        return ForumNewsTests.test_load_top_10_threads_page(self)

    def test_load_add_news_page(self):
        """Test case: Load add news page."""
        return ForumNewsTests.test_load_add_news_page(self)

    def test_add_news_page_mandatory_fields_are_marked_with_asterisk(self):
        """Test case: Add news page mandatory fields are marked with asterisk."""
        return ForumNewsTests.test_add_news_page_mandatory_fields_are_marked_with_asterisk(self)

    def test_create_news_with_valid_data(self):
        """Test case: Create news with valid data."""
        return ForumNewsTests.test_create_news_with_valid_data(self)

    def test_create_news_with_blank_display_text(self):
        """Test case: Create news with blank display text."""
        return ForumNewsTests.test_create_news_with_blank_display_text(self)

    def test_create_news_with_blank_link(self):
        """Test case: Create news with blank link."""
        return ForumNewsTests.test_create_news_with_blank_link(self)

    def test_click_add_news_cancel_button(self):
        """Test case: Click add news cancel button."""
        return ForumNewsTests.test_click_add_news_cancel_button(self)

    def test_create_news_with_invalid_link_format(self):
        """Test case: Create news with invalid link format."""
        return ForumNewsTests.test_create_news_with_invalid_link_format(self)

    def test_create_news_using_enter_key(self):
        """Test case: Create news using enter key."""
        return ForumNewsTests.test_create_news_using_enter_key(self)

    def test_create_news_with_duplicate_data(self):
        """Test case: Create news with duplicate data."""
        return ForumNewsTests.test_create_news_with_duplicate_data(self)

    def test_create_news_with_trailing_spaces(self):
        """Test case: Create news with trailing spaces."""
        return ForumNewsTests.test_create_news_with_trailing_spaces(self)

    def test_load_edit_news_page(self):
        """Test case: Load edit news page."""
        return ForumNewsTests.test_load_edit_news_page(self)

    def test_click_edit_news_cancel_button(self):
        """Test case: Click edit news cancel button."""
        return ForumNewsTests.test_click_edit_news_cancel_button(self)

    def test_update_news_with_blank_display_text(self):
        """Test case: Update news with blank display text."""
        return ForumNewsTests.test_update_news_with_blank_display_text(self)

    def test_update_news_with_blank_link(self):
        """Test case: Update news with blank link."""
        return ForumNewsTests.test_update_news_with_blank_link(self)

    def test_edit_news_with_valid_data(self):
        """Test case: Edit news with valid data."""
        return ForumNewsTests.test_edit_news_with_valid_data(self)

    def test_edit_news_with_invalid_link(self):
        """Test case: Edit news with invalid link."""
        return ForumNewsTests.test_edit_news_with_invalid_link(self)

    def test_edit_news_with_trailing_spaces(self):
        """Test case: Edit news with trailing spaces."""
        return ForumNewsTests.test_edit_news_with_trailing_spaces(self)

    def test_authentication_add_news(self):
        """Test case: Authentication add news."""
        return ForumNewsTests.test_authentication_add_news(self)


    # ---- BrowseSearchTests -------------------------------------------
    def test_eventline(self):
        """Test case: Eventline."""
        return BrowseSearchTests.test_eventline(self)

    def test_browse_namespace_filter(self):
        """Test case: Browse namespace filter."""
        return BrowseSearchTests.test_browse_namespace_filter(self)

    def test_browse_algorithm_filter(self):
        """Test case: Browse algorithm filter."""
        return BrowseSearchTests.test_browse_algorithm_filter(self)

    def test_advanced_search_nickname_tab_navigation(self):
        """Test case: Advanced search nickname tab navigation."""
        return BrowseSearchTests.test_advanced_search_nickname_tab_navigation(self)

    def test_browse_videos(self):
        """Test case: Browse videos."""
        return BrowseSearchTests.test_browse_videos(self)

    def test_browse_help(self):
        """Test case: Browse help."""
        return BrowseSearchTests.test_browse_help(self)

    def test_browse_notification(self):
        """Test case: Browse notification."""
        return BrowseSearchTests.test_browse_notification(self)

    def test_browse_profile_setting(self):
        """Test case: Browse profile setting."""
        return BrowseSearchTests.test_browse_profile_setting(self)

    def test_browse_profile_setting_account_setting(self):
        """Test case: Browse profile setting account setting."""
        return BrowseSearchTests.test_browse_profile_setting_account_setting(self)

    def test_footer_browse_button(self):
        """Test case: Footer browse button."""
        return BrowseSearchTests.test_footer_browse_button(self)

    def test_footer_upload_file_button(self):
        """Test case: Footer upload file button."""
        return BrowseSearchTests.test_footer_upload_file_button(self)

    def test_footer_sitemap_button(self):
        """Test case: Footer sitemap button."""
        return BrowseSearchTests.test_footer_sitemap_button(self)

    def test_footer_videos_button(self):
        """Test case: Footer videos button."""
        return BrowseSearchTests.test_footer_videos_button(self)

    def test_footer_help_button(self):
        """Test case: Footer help button."""
        return BrowseSearchTests.test_footer_help_button(self)

    def test_footer_white_paper_button(self):
        """Test case: Footer white paper button."""
        return BrowseSearchTests.test_footer_white_paper_button(self)

    def test_footer_jobs_button(self):
        """Test case: Footer jobs button."""
        return BrowseSearchTests.test_footer_jobs_button(self)

    def test_footer_privacy_policy_button(self):
        """Test case: Footer privacy policy button."""
        return BrowseSearchTests.test_footer_privacy_policy_button(self)

    def test_footer_term_and_services_button(self):
        """Test case: Footer term and services button."""
        return BrowseSearchTests.test_footer_term_and_services_button(self)

    def test_footer_upload_file_button_repeat_navigation(self):
        """Test case: Footer upload file button repeat navigation."""
        return BrowseSearchTests.test_footer_upload_file_button_repeat_navigation(self)

    def test_authentication_header_browse_pge(self):
        """Test case: Authentication header browse pge."""
        return BrowseSearchTests.test_authentication_header_browse_pge(self)

    def test_authentication_header_videos(self):
        """Test case: Authentication header videos."""
        return BrowseSearchTests.test_authentication_header_videos(self)

    def test_authentication_header_help(self):
        """Test case: Authentication header help."""
        return BrowseSearchTests.test_authentication_header_help(self)

    def test_authentication_footer_browse(self):
        """Test case: Authentication footer browse."""
        return BrowseSearchTests.test_authentication_footer_browse(self)

    def test_authentication_footer_upload_file(self):
        """Test case: Authentication footer upload file."""
        return BrowseSearchTests.test_authentication_footer_upload_file(self)

    def test_authentication_footer_videos(self):
        """Test case: Authentication footer videos."""
        return BrowseSearchTests.test_authentication_footer_videos(self)

    def test_authentication_footer_help(self):
        """Test case: Authentication footer help."""
        return BrowseSearchTests.test_authentication_footer_help(self)

    def test_authentication_footer_white_paper(self):
        """Test case: Authentication footer white paper."""
        return BrowseSearchTests.test_authentication_footer_white_paper(self)

    def test_authentication_footer_policy(self):
        """Test case: Authentication footer policy."""
        return BrowseSearchTests.test_authentication_footer_policy(self)

    def test_authentication_footer_terms_and_services(self):
        """Test case: Authentication footer terms and services."""
        return BrowseSearchTests.test_authentication_footer_terms_and_services(self)

    def test_upload_file_manager_search_and_reset(self):
        """Test case: Upload file manager search and reset."""
        return BrowseSearchTests.test_upload_file_manager_search_and_reset(self)

    def test_categories_page(self):
        """Test case: Categories page."""
        return BrowseSearchTests.test_categories_page(self)

    def test_elastic_search_count(self):
        """Test case: Elastic search count."""
        return BrowseSearchTests.test_elastic_search_count(self)

    def test_videos_thumbnail(self):
        """Test case: Videos thumbnail."""
        return BrowseSearchTests.test_videos_thumbnail(self)

    def test_tree_search_crash(self):
        """Test case: Tree search crash."""
        return BrowseSearchTests.test_tree_search_crash(self)

    def test_agree_search_crash(self):
        """Test case: Agree search crash."""
        return BrowseSearchTests.test_agree_search_crash(self)

    def test_direct_supported_search(self):
        """Test case: Direct supported search."""
        return BrowseSearchTests.test_direct_supported_search(self)

    def test_delegated_supported_search(self):
        """Test case: Delegated supported search."""
        return BrowseSearchTests.test_delegated_supported_search(self)


    # ---- ProfileUploadAccessTests ------------------------------------
    def test_verify_submitter_nick_name_link_on_user_profile(self):
        """Test case: Verify submitter nick name link on user profile."""
        return ProfileUploadAccessTests.test_verify_submitter_nick_name_link_on_user_profile(self)

    def test_upload_files(self):
        """Test case: Upload files."""
        return ProfileUploadAccessTests.test_upload_files(self)

    def test_upload_profile_picture(self):
        """Test case: Upload profile picture."""
        return ProfileUploadAccessTests.test_upload_profile_picture(self)

    def test_view_profile_picture(self):
        """Test case: View profile picture."""
        return ProfileUploadAccessTests.test_view_profile_picture(self)

    def test_delete_profile_picture(self):
        """Test case: Delete profile picture."""
        return ProfileUploadAccessTests.test_delete_profile_picture(self)

    def test_delete_profile_picture_when_no_image_exists(self):
        """Test case: Delete profile picture when no image exists."""
        return ProfileUploadAccessTests.test_delete_profile_picture_when_no_image_exists(self)

    def test_alphabets_for_no_profile_image(self):
        """Test case: Alphabets for no profile image."""
        return ProfileUploadAccessTests.test_alphabets_for_no_profile_image(self)

    def test_authentication_expiry_for_upload_file(self):
        """Test case: Authentication expiry for upload file."""
        return ProfileUploadAccessTests.test_authentication_expiry_for_upload_file(self)

    def test_authentication_expiry_for_account_setting(self):
        """Test case: Authentication expiry for account setting."""
        return ProfileUploadAccessTests.test_authentication_expiry_for_account_setting(self)

    def test_authentication_expiry_for_nicknames(self):
        """Test case: Authentication expiry for nicknames."""
        return ProfileUploadAccessTests.test_authentication_expiry_for_nicknames(self)

    def test_authentication_expiry_for_user_preference(self):
        """Test case: Authentication expiry for user preference."""
        return ProfileUploadAccessTests.test_authentication_expiry_for_user_preference(self)

    def test_authentication_expiry_for_subscriptions(self):
        """Test case: Authentication expiry for subscriptions."""
        return ProfileUploadAccessTests.test_authentication_expiry_for_subscriptions(self)

    def test_authentication_social_oauth_verification(self):
        """Test case: Authentication social oauth verification."""
        return ProfileUploadAccessTests.test_authentication_social_oauth_verification(self)

    def test_authentication_change_password(self):
        """Test case: Authentication change password."""
        return ProfileUploadAccessTests.test_authentication_change_password(self)

    def test_authentication_homepage(self):
        """Test case: Authentication homepage."""
        return ProfileUploadAccessTests.test_authentication_homepage(self)

    def test_authentication_notification_page(self):
        """Test case: Authentication notification page."""
        return ProfileUploadAccessTests.test_authentication_notification_page(self)

    def test_authentication_notification_delete(self):
        """Test case: Authentication notification delete."""
        return ProfileUploadAccessTests.test_authentication_notification_delete(self)

    def test_upload_file_with_admin(self):
        """Test case: Upload file with admin."""
        return ProfileUploadAccessTests.test_upload_file_with_admin(self)

    def test_upload_file_less_than_5mb(self):
        """Test case: Upload file less than 5mb."""
        return ProfileUploadAccessTests.test_upload_file_less_than_5mb(self)

    def test_upload_file_more_than_5mb(self):
        """Test case: Upload file more than 5mb."""
        return ProfileUploadAccessTests.test_upload_file_more_than_5mb(self)

    def test_upload_in_create_new_folder(self):
        """Test case: Upload in create new folder."""
        return ProfileUploadAccessTests.test_upload_in_create_new_folder(self)

    def test_upload_file_in_new_folder(self):
        """Test case: Upload file in new folder."""
        return ProfileUploadAccessTests.test_upload_file_in_new_folder(self)

    def test_upload_file_manager_toggle_views(self):
        """Test case: Upload file manager toggle views."""
        return ProfileUploadAccessTests.test_upload_file_manager_toggle_views(self)

    def test_upload_file_manager_file_actions_menu(self):
        """Test case: Upload file manager file actions menu."""
        return ProfileUploadAccessTests.test_upload_file_manager_file_actions_menu(self)

    def test_upload_file_manager_delete_modal_cancel(self):
        """Test case: Upload file manager delete modal cancel."""
        return ProfileUploadAccessTests.test_upload_file_manager_delete_modal_cancel(self)

    def test_profile_page_name_change(self):
        """Test case: Profile page name change."""
        return ProfileUploadAccessTests.test_profile_page_name_change(self)

    def test_notifications_filters_matrix(self):
        """Test case: Notifications filters matrix."""
        return ProfileUploadAccessTests.test_notifications_filters_matrix(self)

    def test_notifications_mark_all_read_cancel(self):
        """Test case: Notifications mark all read cancel."""
        return ProfileUploadAccessTests.test_notifications_mark_all_read_cancel(self)

    def test_notifications_delete_all_cancel(self):
        """Test case: Notifications delete all cancel."""
        return ProfileUploadAccessTests.test_notifications_delete_all_cancel(self)

    def test_notifications_load_more_if_available(self):
        """Test case: Notifications load more if available."""
        return ProfileUploadAccessTests.test_notifications_load_more_if_available(self)

    def test_direct_supported_remove_modal_cancel(self):
        """Test case: Direct supported remove modal cancel."""
        return ProfileUploadAccessTests.test_direct_supported_remove_modal_cancel(self)

    def test_delegated_supported_remove_modal_cancel(self):
        """Test case: Delegated supported remove modal cancel."""
        return ProfileUploadAccessTests.test_delegated_supported_remove_modal_cancel(self)

    def test_social_auth_link_controls_visible(self):
        """Test case: Social auth link controls visible."""
        return ProfileUploadAccessTests.test_social_auth_link_controls_visible(self)

    def test_profile_page_nickname_tab(self):
        """Test case: Profile page nickname tab."""
        return ProfileUploadAccessTests.test_profile_page_nickname_tab(self)

    def test_profile_page_preferences_tab(self):
        """Test case: Profile page preferences tab."""
        return ProfileUploadAccessTests.test_profile_page_preferences_tab(self)

    def test_profile_page_mysubscription_tab(self):
        """Test case: Profile page mysubscription tab."""
        return ProfileUploadAccessTests.test_profile_page_mysubscription_tab(self)

    def test_profile_page_account_setting_social_auth_tab(self):
        """Test case: Profile page account setting social auth tab."""
        return ProfileUploadAccessTests.test_profile_page_account_setting_social_auth_tab(self)

    def test_profile_page_account_setting_password_tab(self):
        """Test case: Profile page account setting password tab."""
        return ProfileUploadAccessTests.test_profile_page_account_setting_password_tab(self)

    def test_profile_setting_public_crash(self):
        """Test case: Profile setting public crash."""
        return ProfileUploadAccessTests.test_profile_setting_public_crash(self)

    def test_asp_old_urls_for_support(self):
        """Test case: Asp old urls for support."""
        return ProfileUploadAccessTests.test_asp_old_urls_for_support(self)


    # ---- BacklogTests ------------------------------------------------
    @pytest.mark.no_browser
    def test_backlog_advanced_support_management_reorder_and_petitions(self):
        """Backlog: support reorder persistence, petitions, and confirm-remove workflows."""
        return BacklogTests.test_backlog_advanced_support_management_reorder_and_petitions(self)

    @pytest.mark.no_browser
    def test_backlog_notifications_single_item_read_and_confirm_actions(self):
        """Backlog: single-item read behavior and confirmed mark/delete all notifications."""
        return BacklogTests.test_backlog_notifications_single_item_read_and_confirm_actions(self)

    @pytest.mark.no_browser
    def test_backlog_ai_agents_register_edit_password_deactivate(self):
        """Backlog: AI-agent lifecycle flows from account settings."""
        return BacklogTests.test_backlog_ai_agents_register_edit_password_deactivate(self)

    @pytest.mark.no_browser
    def test_backlog_advanced_search_filter_combination_result_counts(self):
        """Backlog: deeper filter-combination assertions with deterministic result counts."""
        return BacklogTests.test_backlog_advanced_search_filter_combination_result_counts(self)

    @pytest.mark.no_browser
    def test_backlog_file_manager_download_rename_delete_sort_persistence(self):
        """Backlog: file manager persistence checks for download/rename/delete/sort."""
        return BacklogTests.test_backlog_file_manager_download_rename_delete_sort_persistence(self)

    @pytest.mark.no_browser
    def test_backlog_preferred_topics_save_discard_and_wizard_flows(self):
        """Backlog: preferred topics save/discard validation and wizard finish/skip flows."""
        return BacklogTests.test_backlog_preferred_topics_save_discard_and_wizard_flows(self)

    @pytest.mark.no_browser
    def test_backlog_social_account_link_unlink(self):
        """Backlog: social account link/unlink workflows with provider callbacks."""
        return BacklogTests.test_backlog_social_account_link_unlink(self)


    # ---- MiscTests ---------------------------------------------------
    def test_click_on_join_now(self):
        """Test case: Click on join now."""
        return MiscTests.test_click_on_join_now(self)

    def test_registration_with_valid_credential(self):
        """Test case: Registration with valid credential."""
        return MiscTests.test_registration_with_valid_credential(self)

    def test_registration_first_name_with_spaces(self):
        """Test case: Registration first name with spaces."""
        return MiscTests.test_registration_first_name_with_spaces(self)

    def test_registration_with_blank_first_name(self):
        """Test case: Registration with blank first name."""
        return MiscTests.test_registration_with_blank_first_name(self)

    def test_registration_with_blank_email(self):
        """Test case: Registration with blank email."""
        return MiscTests.test_registration_with_blank_email(self)

    def test_registration_with_blank_last_name(self):
        """Test case: Registration with blank last name."""
        return MiscTests.test_registration_with_blank_last_name(self)

    def test_registration_with_blank_password(self):
        """Test case: Registration with blank password."""
        return MiscTests.test_registration_with_blank_password(self)

    def test_registration_with_invalid_password_length(self):
        """Test case: Registration with invalid password length."""
        return MiscTests.test_registration_with_invalid_password_length(self)

    def test_registration_with_invalid_email(self):
        """Test case: Registration with invalid email."""
        return MiscTests.test_registration_with_invalid_email(self)

    def test_verify_the_functionality_of_registration_with_entering_data_in_mandatory_fields(self):
        """Test case: Verify the functionality of registration with entering data in mandatory fields."""
        return MiscTests.test_verify_the_functionality_of_registration_with_entering_data_in_mandatory_fields(self)

    def test_verify_the_functionality_0f_registration_with_entering_data_in_mobile_number_field(self):
        """Test case: Verify the functionality 0f registration with entering data in mobile number field."""
        return MiscTests.test_verify_the_functionality_0f_registration_with_entering_data_in_mobile_number_field(self)

    def test_verify_one_time_request_code_with_valid_credentials(self):
        """Test case: Verify one time request code with valid credentials."""
        return MiscTests.test_verify_one_time_request_code_with_valid_credentials(self)

    def test_registration_with_blank_confirm_password(self):
        """Test case: Registration with blank confirm password."""
        return MiscTests.test_registration_with_blank_confirm_password(self)

    def test_registration_with_mismatched_passwords(self):
        """Test case: Registration with mismatched passwords."""
        return MiscTests.test_registration_with_mismatched_passwords(self)

    def test_registration_with_invalid_mobile_number(self):
        """Test case: Registration with invalid mobile number."""
        return MiscTests.test_registration_with_invalid_mobile_number(self)

    def test_registration_social_providers_are_available(self):
        """Test case: Registration social providers are available."""
        return MiscTests.test_registration_social_providers_are_available(self)

    def test_load_my_participation_page(self):
        """Test case: Load my participation page."""
        return MiscTests.test_load_my_participation_page(self)

    def test_create_new_with_blank_fields(self):
        """Test case: Create new with blank fields."""
        return MiscTests.test_create_new_with_blank_fields(self)

    def test_cafe_text_in_address_bar(self):
        """Test case: Cafe text in address bar."""
        return MiscTests.test_cafe_text_in_address_bar(self)

    def test_update_first_name(self):
        """Test case: Update first name."""
        return MiscTests.test_update_first_name(self)

    def test_update_last_name(self):
        """Test case: Update last name."""
        return MiscTests.test_update_last_name(self)

    def test_update_date_of_birth(self):
        """Test case: Update date of birth."""
        return MiscTests.test_update_date_of_birth(self)

    def test_update_gender(self):
        """Test case: Update gender."""
        return MiscTests.test_update_gender(self)

    def test_update_phone_number(self):
        """Test case: Update phone number."""
        return MiscTests.test_update_phone_number(self)

    def test_update_address_1(self):
        """Test case: Update address 1."""
        return MiscTests.test_update_address_1(self)


def _apply_test_markers():
    """Mirror of main.py._apply_test_markers so slicing by marker still works."""
    smoke_tests = {
        "test_click_on_join_now",
        "test_click_on_login_button",
        "test_login_with_registered_credentials",
        "test_create_topic_name_with_valid_data",
        "test_create_camp_with_valid_data",
        "test_add_camp_statement_with_valid_data",
        "test_create_thread_with_valid_data",
    }
    destructive_keywords = ("delete", "remove", "update", "edit", "create_", "upload")
    slow_keywords = ("upload", "search", "history", "notification")

    for attr_name in dir(TestPages):
        if not attr_name.startswith("test_"):
            continue
        test_func = getattr(TestPages, attr_name)
        if not callable(test_func):
            continue
        marks = list(getattr(test_func, "pytestmark", []))
        marks.append(pytest.mark.regression)
        if attr_name in smoke_tests:
            marks.append(pytest.mark.smoke)
        lowered = attr_name.lower()
        if any(k in lowered for k in destructive_keywords):
            marks.append(pytest.mark.destructive)
        if any(k in lowered for k in slow_keywords):
            marks.append(pytest.mark.slow)
        test_func.pytestmark = marks


_apply_test_markers()


if __name__ == "__main__":
    import sys as _sys

    raise SystemExit(pytest.main([__file__, *_sys.argv[1:]]))
