import random
import string
import time
import unittest
from datetime import datetime
from subprocess import run

import pytest
import requests
import xmlrunner as xmlrunner
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver import ActionChains
from selenium.webdriver.common import keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from urllib3.util import response
from xmlrunner import *

from CanonizerAccountPage import CanonizerPofilePage
from CanonizerAddEditNewsPage import CanonizerAddNewsPage, CanonizerEditNewsPage
from CanonizerAdvancedSettingsPage import CanonizerAdvancedSettingsPage
from CanonizerAuthenticationPage import CanonizerAuthenticationPage
from CanonizerBrowsePage import CanonizerBrowsePage
from CanonizerCampForum import CanonizerCampForumPage
from CanonizerCampStatementPage import CanonizerCampStatementPage
from CanonizerCreateUpdateCampPage import CanonizerCreateCampPage, CanonizerEditCampPage
from CanonizerCreateUpdateTopicPage import CanonizerCreateNewTopic, CanonizerUpdateTopicPage
from CanonizerLoginPage import CanonizerLoginPage
from CanonizerProfileUpdatePage import CanonizerPofileUpdatePage
from CanonizerRegistrationPage import CanonizerRegisterPage
from CanonizerSearchPage import CanonizerSearchPage
from CanonizerTestCases import test_cases
from CanonizerUploadFile import CanonizerUploadFile
from Config import *
from Identifiers import *
from Identifiers import CreateTopicIdentifiers, RegistrationPageIdentifiers
