#!/usr/bin/env python
"""Generate ``test_all.py`` — one physical ``def test_*`` per test.

The suite is normally composed by multiple inheritance in ``main.py``, so the
editor never sees a ``def test_`` line to hang a "Run Test" gutter icon on.
This script writes a flat module where every test is a real one-line method
that delegates to the actual implementation in ``test_suites/*_tests.py``.

Run from the project root:

    .venv/bin/python tools/gen_test_all.py

Then VS Code (with pytest discovery pointed at test_all.py) shows Run/Debug
icons on each test. Re-run this whenever tests are added/removed/renamed.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from test_suites import (  # noqa: E402
    AuthRegistrationTests,
    BacklogTests,
    BrowseSearchTests,
    CampTests,
    ForumNewsTests,
    MiscTests,
    ProfileUploadAccessTests,
    StatementTests,
    TopicTests,
)

# Same order main.py mixes them, so nodeids line up with the existing suite.
MIXINS = [
    ("AuthRegistrationTests", AuthRegistrationTests),
    ("TopicTests", TopicTests),
    ("CampTests", CampTests),
    ("StatementTests", StatementTests),
    ("ForumNewsTests", ForumNewsTests),
    ("BrowseSearchTests", BrowseSearchTests),
    ("ProfileUploadAccessTests", ProfileUploadAccessTests),
    ("BacklogTests", BacklogTests),
    ("MiscTests", MiscTests),
]

HEADER = '''\
"""AUTO-GENERATED by tools/gen_test_all.py — do not edit by hand.

Flat view of the whole Canonizer UI suite: one physical ``def test_*`` per
case so VS Code shows a Run/Debug gutter icon on every test. Each method just
calls the real implementation in ``test_suites/*_tests.py`` — no logic lives
here. Regenerate after changing the suites:

    .venv/bin/python tools/gen_test_all.py
"""
import pytest

from test_suites import (
    BaseFlow,
    AuthRegistrationTests,
    TopicTests,
    CampTests,
    StatementTests,
    ForumNewsTests,
    BrowseSearchTests,
    ProfileUploadAccessTests,
    BacklogTests,
    MiscTests,
)


class TestPages(
    BaseFlow,
    AuthRegistrationTests,
    TopicTests,
    CampTests,
    StatementTests,
    ForumNewsTests,
    BrowseSearchTests,
    ProfileUploadAccessTests,
    BacklogTests,
    MiscTests,
):
    """Every test as a one-line delegating wrapper (see module docstring)."""
'''

FOOTER = '''

def _apply_test_markers():
    """Mirror of main.py._apply_test_markers so slicing by marker still works."""
    smoke_tests = {
        "test_click_on_join_now",
        "test_click_on_login_button",
        "test_login_with_registered_credentials",
        "test_create_topic_name_with_valid_data",
        "test_create_camp_with_valid_data",
        "test_add_camp_statement_with_valid_data",
        "test_create_thread_with_valid_data",
    }
    destructive_keywords = ("delete", "remove", "update", "edit", "create_", "upload")
    slow_keywords = ("upload", "search", "history", "notification")

    for attr_name in dir(TestPages):
        if not attr_name.startswith("test_"):
            continue
        test_func = getattr(TestPages, attr_name)
        if not callable(test_func):
            continue
        marks = list(getattr(test_func, "pytestmark", []))
        marks.append(pytest.mark.regression)
        if attr_name in smoke_tests:
            marks.append(pytest.mark.smoke)
        lowered = attr_name.lower()
        if any(k in lowered for k in destructive_keywords):
            marks.append(pytest.mark.destructive)
        if any(k in lowered for k in slow_keywords):
            marks.append(pytest.mark.slow)
        test_func.pytestmark = marks


_apply_test_markers()


if __name__ == "__main__":
    import sys as _sys

    raise SystemExit(pytest.main([__file__, *_sys.argv[1:]]))
'''


def mark_name(m):
    return getattr(m, "name", getattr(getattr(m, "mark", None), "name", ""))


def build_method(cls_name, name, func):
    marks = list(getattr(func, "pytestmark", []))
    decos = []
    extra_params = []
    for m in marks:
        nm = mark_name(m)
        if nm == "parametrize":
            argnames, argvals = m.args[0], m.args[1]
            decos.append(f"    @pytest.mark.parametrize({argnames!r}, {argvals!r})")
            extra_params += [a.strip() for a in argnames.split(",") if a.strip()]
        elif nm == "no_browser":
            decos.append("    @pytest.mark.no_browser")
        # other marks (regression/smoke/…) are re-applied by _apply_test_markers()

    params = ", ".join(["self", *extra_params])
    call = ", ".join(["self", *extra_params])
    doc = (func.__doc__ or "").strip().splitlines()
    doc_line = f'        """{doc[0]}"""\n' if doc else ""

    out = []
    out.extend(decos)
    out.append(f"    def {name}({params}):")
    if doc_line:
        out.append(doc_line.rstrip("\n"))
    out.append(f"        return {cls_name}.{name}({call})")
    out.append("")
    return "\n".join(out)


def main():
    blocks = []
    count = 0
    for cls_name, cls in MIXINS:
        section = [f"\n    # ---- {cls_name} " + "-" * (60 - len(cls_name))]
        for name, func in vars(cls).items():
            if not name.startswith("test_") or not callable(func):
                continue
            section.append(build_method(cls_name, name, func))
            count += 1
        blocks.append("\n".join(section))

    text = HEADER + "\n" + "\n".join(blocks) + FOOTER
    out_path = ROOT / "test_all.py"
    out_path.write_text(text, encoding="utf-8")
    print(f"Wrote {out_path} with {count} test wrappers across {len(MIXINS)} suites.")


if __name__ == "__main__":
    main()
